---
title: "Jasen_Regularization"
author: "Jasen Zhang"
date: "11/21/2020"
output: pdf_document
---

# 1 Loading the Data


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(gplots)
library(glmnet)
df <- read.csv('cancer_registry.csv') %>%
  mutate(PctSomeCol18_24 = 100 - PctNoHS18_24 - PctHS18_24 - PctBachDeg18_24) %>%
  filter(incidenceRate < 1000) %>%
  filter(avgAnnCount < 20000) %>%
  filter(MedianAge < 200) %>%
  filter(AvgHouseholdSize > 1)

df <- na.omit(df)

df <- df %>% mutate(sample_ID = 1:nrow(df))
```


# 2 Modifying the Design Matrix

```{r}
vars <- colnames(df)
misc_vars <- c('binnedInc', 'Geography', 'sample_ID', 'TARGET_deathRate')
vars_1 <- setdiff(vars, misc_vars)

response_vars <- c('TARGET_deathRate')
predict_vars <- paste(vars_1, collapse = ' + ')

df <- df %>% select(- c('binnedInc', 'Geography'))
df <- data.frame(sapply(df, as.numeric))
```


# 3 Splitting Test and Training Set

## Arbitrarily chose 10% to be test set

```{r message=FALSE}
set.seed(221)
test_set_index <- sample(1:nrow(df), floor(nrow(df))/10)
train_set_index <- setdiff(1:nrow(df), test_set_index)

test <- df[test_set_index,]
train <- df[train_set_index,]

test_y <- test %>% select(response_vars)
test_x <- test %>% select(vars_1)
train_y <- train %>% select(response_vars)
train_x <- train %>% select(vars_1)
```

# 4 Lasso + Leave one out Cross Validation

## 10 folds since that's default

```{r}

lambda_seq <- 10^seq(2, -2, by = -.05)

cv_output <- cv.glmnet(as.matrix(train_x), as.matrix(train_y),
                       alpha = 1, lambda = lambda_seq)

best_lambda <- cv_output$lambda.min

lasso_best <- glmnet(as.matrix(train_x), as.matrix(train_y), alpha = 1, lambda = best_lambda)
pred <- predict(lasso_best, s = best_lambda, newx = as.matrix(test_x))
pred_train_y <- predict(lasso_best, s = best_lambda, newx = as.matrix(train_x))

```

# 5 Plotting Y_hat vs Y for training set

```{r}
train_results <- data.frame(train_y, pred_train_y)
colnames(train_results) <- c('y_true', 'y_hat')
R_squared <- as.numeric(unname(cor(train_y, pred_train_y)))
R_squared <- sprintf("%.3f", round(R_squared,3))
R_squared_label <- paste('R^2 = ', R_squared)

g <- ggplot(train_results) + 
  geom_point(aes(x = y_true, y= y_hat)) + 
  geom_line(aes(x = y_true, y = y_true))  +
  geom_label(label = R_squared_label, x = 100, y = 275, label.padding = unit(0.55, "lines"),
    label.size = 0.35,
    color = "black",
    fill="#69b3a2")

g
```

# 6 Plotting Y_hat vs Y for test set

```{r}
test_results <- data.frame(test_y, pred)
colnames(test_results) <- c('y_true', 'y_hat')
R_squared <- as.numeric(unname(cor(test_y, pred)))
R_squared <- sprintf("%.3f", round(R_squared,3))
R_squared_label <- paste('R^2 = ', R_squared)

g <- ggplot(test_results) + 
  geom_point(aes(x = y_true, y= y_hat)) + 
  geom_line(aes(x = y_true, y = y_true))  +
  geom_label(label = R_squared_label, x = 125, y = 250, label.padding = unit(0.55, "lines"),
    label.size = 0.35,
    color = "black",
    fill="#69b3a2")

g
```


